# Generated by Django 4.0.6 on 2023-09-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='name_further',
            field=models.CharField(default='toto', max_length=255),
        ),
    ]
