# Generated by Django 4.0.6 on 2023-09-06 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='user_csvs/')),
                ('category', models.CharField(choices=[('Type1', 'Email'), ('Type2', 'Phone')], max_length=10)),
                ('name', models.CharField(default='safecsv', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
