# Generated by Django 4.0.6 on 2023-09-13 15:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercsv',
            name='csv_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='csv_file'),
        ),
    ]
