# Generated by Django 4.0.6 on 2023-09-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='functional_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userpdf',
            name='non_functional_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
