# Generated by Django 4.0.6 on 2023-09-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_userpdf_name_further'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpdf',
            name='name_further',
        ),
    ]
