# Generated by Django 4.0.6 on 2023-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_userpdf_functional_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='consultant_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userpdf',
            name='name_of_client_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userpdf',
            name='name_of_project',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userpdf',
            name='type_of_project',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
