# Generated by Django 4.0.6 on 2023-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_university_userpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='name',
            field=models.CharField(default='safequeen', max_length=255),
        ),
    ]
