# Generated by Django 4.0.6 on 2023-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_userpdf_consultant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
