# Generated by Django 4.0.6 on 2023-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_userpdf_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpdf',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
