# Generated by Django 4.0.6 on 2023-09-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_user_reset_password_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_password_code',
            new_name='password_reset_code',
        ),
    ]
