# Generated by Django 4.0.6 on 2023-09-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/PHOTO-2023-09-04-11-14-23_vEOc0v8.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
