# Generated by Django 4.0.6 on 2023-10-02 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0005_alter_userpdf_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdf',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userpdf',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AddField(
            model_name='userpdf',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='back_end.university'),
        ),
    ]
